[target.riscv32imac-unknown-none-elf]
runner = "probe-rs run --chip=esp32c6 --preverify --always-print-stacktrace --no-location --catch-hardfault"

[env]
DEFMT_LOG="info"

[build]
rustflags = [
  "-C", "force-frame-pointers",
  "-Z", "stack-protector=all",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core"]
